In [21]:
import csv
from pathlib import Path
import pandas as pd

In [22]:
PATH = "C:/Users/abram/PycharmProjects/DrivenData_DAT_Parkinsons/src/outputs/scan_centres.csv"

In [23]:
data = pd.read_csv(PATH)
data.head()

,uid,pathological,x_centre,y_centre,z_centre,x_voxel_size,y_voxel_size,z_voxel_size
0,xaji0y6d,0,48,62,37,2.46,2.46,2.46
1,pbhsahxt,0,51,65,25,2.46,2.46,2.46
2,hv3a3zmf,0,47,65,26,2.46,2.46,2.46
3,8mdd4v30,0,48,62,33,2.46,2.46,2.46
4,t9nt3w5u,1,48,55,30,2.46,2.46,2.46

In [24]:
data["z_voxel_size"].value_counts()
# data.groupby('z_voxel_size').value_counts()

z_voxel_size
2.46000    528
3.90000    254
2.30000    207
2.39760    143
3.89537     71
3.00000     67
1.50000     32
3.30000     26
4.00000     10
3.59095      9
4.41960      9
2.40000      6
Name: count, dtype: int64

In [25]:
data["x_voxel_size"].value_counts()

x_voxel_size
2.46000    528
3.89537    325
2.30000    207
2.39760    149
3.29567     26
1.46827     25
3.30469     13
2.00000     10
3.59095      9
4.41960      9
1.65352      5
1.61922      3
1.63980      3
1.57805      3
1.62608      2
1.45455      2
1.53002      2
1.53688      2
1.59177      2
1.75644      2
1.52316      2
1.50258      2
1.63294      2
1.60548      2
1.68783      2
1.61234      1
1.50944      1
1.57119      1
1.54373      1
1.56433      1
1.58491      1
1.48198      1
1.46141      1
1.59862      1
1.37222      1
1.41338      1
1.67409      1
1.70841      1
1.49572      1
1.74270      1
2.12916      1
2.41509      1
1.74958      1
1.64666      1
2.36020      1
1.88209      1
1.71527      1
2.12692      1
2.01716      1
1.69469      1
Name: count, dtype: int64

In [26]:
data["y_voxel_size"].value_counts()

y_voxel_size
2.46000    528
3.89537    325
2.30000    207
2.39760    149
3.29567     26
1.46827     25
3.30469     13
2.00000     10
3.59095      9
4.41960      9
1.65352      5
1.61922      3
1.63980      3
1.57805      3
1.62608      2
1.45455      2
1.53002      2
1.53688      2
1.59177      2
1.75644      2
1.52316      2
1.50258      2
1.63294      2
1.60548      2
1.68783      2
1.61234      1
1.50944      1
1.57119      1
1.54373      1
1.56433      1
1.58491      1
1.48198      1
1.46141      1
1.59862      1
1.37222      1
1.41338      1
1.67409      1
1.70841      1
1.49572      1
1.74270      1
2.12916      1
2.41509      1
1.74958      1
1.64666      1
2.36020      1
1.88209      1
1.71527      1
2.12692      1
2.01716      1
1.69469      1
Name: count, dtype: int64

In [30]:
data[['x_voxel_size', 'y_voxel_size', 'z_voxel_size']].value_counts()

x_voxel_size  y_voxel_size  z_voxel_size
2.46000       2.46000       2.46000         528
3.89537       3.89537       3.90000         254
2.30000       2.30000       2.30000         207
2.39760       2.39760       2.39760         143
3.89537       3.89537       3.89537          71
3.29567       3.29567       3.30000          26
1.46827       1.46827       1.50000          25
3.30469       3.30469       3.00000          13
2.00000       2.00000       4.00000          10
3.59095       3.59095       3.59095           9
4.41960       4.41960       4.41960           9
2.39760       2.39760       2.40000           6
1.65352       1.65352       3.00000           5
1.61922       1.61922       3.00000           3
1.63980       1.63980       3.00000           3
1.57805       1.57805       3.00000           3
1.62608       1.62608       3.00000           2
1.45455       1.45455       1.50000           2
1.53002       1.53002       3.00000           2
1.53688       1.53688       3.00000           2
1.59177       1.59177       3.00000           2
1.75644       1.75644       3.00000           2
1.52316       1.52316       3.00000           2
1.50258       1.50258       3.00000           2
1.63294       1.63294       3.00000           2
1.60548       1.60548       3.00000           2
1.68783       1.68783       3.00000           2
1.61234       1.61234       3.00000           1
1.50944       1.50944       3.00000           1
1.57119       1.57119       3.00000           1
1.54373       1.54373       3.00000           1
1.56433       1.56433       3.00000           1
1.58491       1.58491       3.00000           1
1.48198       1.48198       1.50000           1
1.46141       1.46141       1.50000           1
1.59862       1.59862       3.00000           1
1.37222       1.37222       1.50000           1
1.41338       1.41338       1.50000           1
1.67409       1.67409       3.00000           1
1.70841       1.70841       3.00000           1
1.49572       1.49572       1.50000           1
1.74270       1.74270       3.00000           1
2.12916       2.12916       3.00000           1
2.41509       2.41509       3.00000           1
1.74958       1.74958       3.00000           1
1.64666       1.64666       3.00000           1
2.36020       2.36020       3.00000           1
1.88209       1.88209       3.00000           1
1.71527       1.71527       3.00000           1
2.12692       2.12692       3.00000           1
2.01716       2.01716       3.00000           1
1.69469       1.69469       3.00000           1
Name: count, dtype: int64

In [31]:
data['x_voxel_size'].describe()

count    1362.000000
mean        2.758013
std         0.715570
min         1.372220
25%         2.397600
50%         2.460000
75%         3.590950
max         4.419600
Name: x_voxel_size, dtype: float64

In [32]:
data['y_voxel_size'].describe()

count    1362.000000
mean        2.758013
std         0.715570
min         1.372220
25%         2.397600
50%         2.460000
75%         3.590950
max         4.419600
Name: y_voxel_size, dtype: float64

In [33]:
data['z_voxel_size'].describe()

count    1362.000000
mean        2.824011
std         0.683351
min         1.500000
25%         2.397600
50%         2.460000
75%         3.895370
max         4.419600
Name: z_voxel_size, dtype: float64

In [51]:
voxel_label_stats = (
    data.groupby(
        ["x_voxel_size", "y_voxel_size", "z_voxel_size"]
    )
    .agg(
        count=("pathological", "size"),
        pathological_count=("pathological", "sum"),
        pathological_rate=("pathological", "mean"),
        uids=("uid", list)
    )
    .reset_index()
    .sort_values("count", ascending=False)
)

voxel_label_stats

,x_voxel_size,y_voxel_size,z_voxel_size,count,pathological_count,pathological_rate,uids
45,2.46000,2.46000,2.46000,528,315,0.596591,"[xaji0y6d, pbhsahxt, hv3a3zmf, 8mdd4v30, t9nt3..."
50,3.89537,3.89537,3.90000,254,147,0.578740,"[t8cq1xgb, ngz6wmdw, 0fgzvrct, lt4q9bc2, be3yq..."
40,2.30000,2.30000,2.30000,207,104,0.502415,"[gfliji18, k0axycel, os6zle6k, whef0vot, qtxhi..."
42,2.39760,2.39760,2.39760,143,65,0.454545,"[om2zkf5b, 1sa3y5t3, 7szpf9s9, ehwhg0u4, 3qlx3..."
49,3.89537,3.89537,3.89537,71,42,0.591549,"[9mx2x18h, afeyuhz1, gv0e38da, ly8ozcyw, d14ve..."
46,3.29567,3.29567,3.30000,26,19,0.730769,"[vzme9wt0, ed8u8noz, oi9wm1sa, v9cng8ta, na6u4..."
4,1.46827,1.46827,1.50000,25,11,0.440000,"[qpgb7r3o, gnzs43c5, eal2w37d, 4ivsolml, 3ifhv..."
47,3.30469,3.30469,3.00000,13,2,0.153846,"[6rv9777t, nqetmni3, 6tx0tbkg, z6d86zch, k63rv..."
36,2.00000,2.00000,4.00000,10,7,0.700000,"[uz2z0kdn, 839ag77q, vqa7izq2, nmnr06dj, zbc7q..."
48,3.59095,3.59095,3.59095,9,3,0.333333,"[8257ge0q, fezac2ex, irjutfvj, 4jtj27yh, ghdil..."
51,4.41960,4.41960,4.41960,9,7,0.777778,"[9vjuhbp9, 9jrd4hqf, 3hzcd3ge, g7f9fzja, bsepr..."
43,2.39760,2.39760,2.40000,6,4,0.666667,"[0iv1ggxr, emdmz5rg, othlqh7p, pcaduvl9, 8b350..."
26,1.65352,1.65352,3.00000,5,2,0.400000,"[ofwb0hpm, cdyk0x65, ysxpnngh, g2qzw3c1, 7fxzv..."
15,1.57805,1.57805,3.00000,3,1,0.333333,"[049enulq, kkzmpjrh, twbozd1a]"
21,1.61922,1.61922,3.00000,3,2,0.666667,"[nz1udbfw, 7ln23y30, 8riec4d1]"
24,1.63980,1.63980,3.00000,3,0,0.000000,"[yjxrpj1e, qkbhb7s9, t64z7w2s]"
11,1.53688,1.53688,3.00000,2,0,0.000000,"[4wsqt26q, oqw9ja2m]"
19,1.60548,1.60548,3.00000,2,1,0.500000,"[ccprhvlz, t7zewviy]"
2,1.45455,1.45455,1.50000,2,0,0.000000,"[ba75uuzp, p8hqmabs]"
10,1.53002,1.53002,3.00000,2,0,0.000000,"[gses6m03, mzsgipps]"
28,1.68783,1.68783,3.00000,2,1,0.500000,"[flul1rsr, 2m71hssb]"
34,1.75644,1.75644,3.00000,2,1,0.500000,"[mufm8zov, ehe2atn2]"
23,1.63294,1.63294,3.00000,2,1,0.500000,"[cj4t0sek, 3c9xqym5]"
9,1.52316,1.52316,3.00000,2,2,1.000000,"[313fpoyi, 832ejx5t]"
7,1.50258,1.50258,3.00000,2,1,0.500000,"[4n89qkns, rwk8r2yk]"
17,1.59177,1.59177,3.00000,2,1,0.500000,"[fnkomv2x, 7875aud9]"
22,1.62608,1.62608,3.00000,2,0,0.000000,"[jgzlma5u, 45bm1enf]"
13,1.56433,1.56433,3.00000,1,0,0.000000,[pkyrybov]
1,1.41338,1.41338,1.50000,1,0,0.000000,[i9nb74x2]
0,1.37222,1.37222,1.50000,1,0,0.000000,[d44k1j6f]
3,1.46141,1.46141,1.50000,1,0,0.000000,[cslqc3c5]
14,1.57119,1.57119,3.00000,1,1,1.000000,[xid4n1u3]
12,1.54373,1.54373,3.00000,1,1,1.000000,[493wxa73]
5,1.48198,1.48198,1.50000,1,0,0.000000,[1r11q7uw]
6,1.49572,1.49572,1.50000,1,0,0.000000,[0w10lbt3]
8,1.50944,1.50944,3.00000,1,0,0.000000,[15z8vmuh]
18,1.59862,1.59862,3.00000,1,0,0.000000,[pk0qtl3q]
16,1.58491,1.58491,3.00000,1,0,0.000000,[akhejla0]
35,1.88209,1.88209,3.00000,1,1,1.000000,[xyvgiui9]
31,1.71527,1.71527,3.00000,1,1,1.000000,[jeyn9382]
29,1.69469,1.69469,3.00000,1,0,0.000000,[k9tr74qg]
30,1.70841,1.70841,3.00000,1,0,0.000000,[xd9css9t]
25,1.64666,1.64666,3.00000,1,0,0.000000,[la8s8hmb]
27,1.67409,1.67409,3.00000,1,1,1.000000,[asifpwio]
20,1.61234,1.61234,3.00000,1,0,0.000000,[3uvulemx]
33,1.74958,1.74958,3.00000,1,0,0.000000,[bbxux1ox]
32,1.74270,1.74270,3.00000,1,0,0.000000,[twdl9zs1]
39,2.12916,2.12916,3.00000,1,0,0.000000,[fflzm764]
41,2.36020,2.36020,3.00000,1,1,1.000000,[vgww4fyb]
37,2.01716,2.01716,3.00000,1,1,1.000000,[6g5g79or]
38,2.12692,2.12692,3.00000,1,0,0.000000,[lx6dut07]
44,2.41509,2.41509,3.00000,1,1,1.000000,[jwtektsg]